# docker-compoase file for development

version: '3'
services:
  devpi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - dev.env
    ports:
    - "3141:3141"
    volumes:
       - data:/devpi

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    env_file:
      - dev.env
    ports:
    - "80:80"
    volumes:
       - data:/devpi

  postgres:
    image: postgres:12
    environment:
    - POSTGRES_USER=devpi_test
    - POSTGRES_PASSWORD=pgpass
    ports:
    - 5432:5432

volumes:
  data:
