FROM nginx:1.16.1
COPY /nginx/etc/ /etc/nginx/
COPY /nginx/bin/ /usr/bin/
CMD /usr/bin/nginx-start
ENV DEBUG=0 \
    WEB_AUTH=0 \
    WEB_DEVPI_LOCKDOWN=0 \
    WEB_SERVER_NAME=localhost \
    WEB_DEVPI_SERVER=devpi:3141 \
    WEB_CLIENT_MAX_BODY_SIZE=64M \
    WEB_PROXY_TIMEOUT=60
